name: groupkash
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  easy_container: ^1.0.3
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_phone_auth_handler: ^1.0.3
  firebase_storage: ^10.2.13
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  provider: ^6.0.3
  google_fonts: ^3.0.0
  http: ^0.13.4
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  passwordfield: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

#
flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product-sans/Product Sans Regular.ttf
        - asset: assets/fonts/product-sans/Product Sans Bold Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
