// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PCMHtzsBnmBhde2p2KYLVfYI0uKR10s',
    appId: '1:675746240391:web:df64d44641032bd358a522',
    messagingSenderId: '675746240391',
    projectId: 'groupkash-app',
    authDomain: 'groupkash-app.firebaseapp.com',
    storageBucket: 'groupkash-app.appspot.com',
    measurementId: 'G-PDGVS943FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2PAE2IGrl3kaEQcixSOgnpuYKOlyD90',
    appId: '1:675746240391:android:af9935d2f1d105fe58a522',
    messagingSenderId: '675746240391',
    projectId: 'groupkash-app',
    storageBucket: 'groupkash-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD-Re8PQUAGXsBeyAGuQEJrmxfLB2npE0',
    appId: '1:675746240391:ios:85a80a715003512158a522',
    messagingSenderId: '675746240391',
    projectId: 'groupkash-app',
    storageBucket: 'groupkash-app.appspot.com',
    androidClientId: '675746240391-svf1tersf84qt1p29od2qi7n23786tkl.apps.googleusercontent.com',
    iosClientId: '675746240391-dkv5q01moif3it7n25vomqcagcfuu3cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupkash',
  );
}
